"""
Unit tests for backend/ingestion/resume_parser.py

Tests cover all edge cases from PHASES.md Phase 1:
  - Empty file (PDF with no pages)
  - Scanned / image-only PDF (no text layer)
  - Malformed DOCX
  - Valid PDF  (happy path)
  - Valid DOCX (happy path)
  - Unsupported extension

Fixtures are generated by tests/fixtures/generate_fixtures.py.
Run that script once before running this test module:

    cd backend
    python tests/fixtures/generate_fixtures.py
    pytest tests/test_resume_parser.py -v
"""

import sys
from pathlib import Path

import pytest

# Make sure the backend package root is on sys.path when running from /backend
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from ingestion.exceptions import ParsingError
from ingestion.resume_parser import parse_resume

FIXTURE_DIR = Path(__file__).parent / "fixtures"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def fixture(name: str) -> Path:
    """Return the absolute path to a named fixture file."""
    return FIXTURE_DIR / name


def assert_fixture_exists(name: str) -> None:
    """Fail with a clear message if a fixture hasn't been generated yet."""
    p = fixture(name)
    if not p.exists():
        pytest.fail(
            f"Fixture '{name}' not found at {p}.\n"
            "Run: python tests/fixtures/generate_fixtures.py"
        )


# ---------------------------------------------------------------------------
# Edge case tests (PHASES.md Phase 1)
# ---------------------------------------------------------------------------


class TestEmptyPDF:
    """A PDF that opens successfully but contains no pages / no text."""

    def test_empty_pdf_raises_parsing_error(self) -> None:
        assert_fixture_exists("empty.pdf")
        with pytest.raises(ParsingError, match="No extractable text"):
            parse_resume(fixture("empty.pdf"))

    def test_empty_pdf_error_is_not_swallowed(self) -> None:
        """Verify the exception propagates (not caught internally)."""
        assert_fixture_exists("empty.pdf")
        raised = False
        try:
            parse_resume(fixture("empty.pdf"))
        except ParsingError:
            raised = True
        assert raised, "ParsingError must propagate — no silent failure"


class TestImageOnlyPDF:
    """A PDF whose only content is an embedded image — no text layer."""

    def test_image_only_pdf_raises_parsing_error(self) -> None:
        assert_fixture_exists("image_only.pdf")
        with pytest.raises(ParsingError, match="No extractable text|image-only|scanned"):
            parse_resume(fixture("image_only.pdf"))

    def test_image_only_pdf_error_mentions_ocr(self) -> None:
        """Error message should tell the user why and what to do."""
        assert_fixture_exists("image_only.pdf")
        with pytest.raises(ParsingError) as exc_info:
            parse_resume(fixture("image_only.pdf"))
        # The error should at least hint that OCR is the missing capability.
        assert "OCR" in str(exc_info.value) or "image" in str(exc_info.value).lower()


class TestMalformedDOCX:
    """A file with a .docx extension that is not a valid ZIP / OOXML."""

    def test_malformed_docx_raises_parsing_error(self) -> None:
        assert_fixture_exists("malformed.docx")
        with pytest.raises(ParsingError, match="[Mm]alformed|[Uu]nreadable|[Cc]ould not open"):
            parse_resume(fixture("malformed.docx"))

    def test_malformed_docx_is_not_swallowed(self) -> None:
        assert_fixture_exists("malformed.docx")
        raised = False
        try:
            parse_resume(fixture("malformed.docx"))
        except ParsingError:
            raised = True
        assert raised


# ---------------------------------------------------------------------------
# Happy path tests
# ---------------------------------------------------------------------------


class TestValidPDF:
    def test_valid_pdf_returns_string(self) -> None:
        assert_fixture_exists("valid_resume.pdf")
        result = parse_resume(fixture("valid_resume.pdf"))
        assert isinstance(result, str)

    def test_valid_pdf_returns_nonempty_text(self) -> None:
        assert_fixture_exists("valid_resume.pdf")
        result = parse_resume(fixture("valid_resume.pdf"))
        assert len(result.strip()) > 0

    def test_valid_pdf_contains_expected_content(self) -> None:
        """The fixture PDF contains 'Skills' — verify extraction works."""
        assert_fixture_exists("valid_resume.pdf")
        result = parse_resume(fixture("valid_resume.pdf"))
        # At least some recognisable content should come through
        assert any(
            word.lower() in result.lower()
            for word in ["skills", "python", "experience", "education"]
        ), f"Expected recognizable resume content in output, got: {result[:200]!r}"


class TestValidDOCX:
    def test_valid_docx_returns_string(self) -> None:
        assert_fixture_exists("valid_resume.docx")
        result = parse_resume(fixture("valid_resume.docx"))
        assert isinstance(result, str)

    def test_valid_docx_returns_nonempty_text(self) -> None:
        assert_fixture_exists("valid_resume.docx")
        result = parse_resume(fixture("valid_resume.docx"))
        assert len(result.strip()) > 0

    def test_valid_docx_contains_expected_content(self) -> None:
        assert_fixture_exists("valid_resume.docx")
        result = parse_resume(fixture("valid_resume.docx"))
        assert any(
            word.lower() in result.lower()
            for word in ["skills", "python", "experience", "education"]
        ), f"Expected recognizable resume content in output, got: {result[:200]!r}"


# ---------------------------------------------------------------------------
# Extension / path tests
# ---------------------------------------------------------------------------


class TestUnsupportedExtension:
    def test_txt_file_raises_parsing_error(self, tmp_path: Path) -> None:
        txt_file = tmp_path / "resume.txt"
        txt_file.write_text("Some resume content", encoding="utf-8")
        with pytest.raises(ParsingError, match="[Uu]nsupported"):
            parse_resume(txt_file)

    def test_nonexistent_file_raises_parsing_error(self, tmp_path: Path) -> None:
        with pytest.raises(ParsingError, match="[Nn]ot found"):
            parse_resume(tmp_path / "ghost.pdf")
