"""Init Schema

Revision ID: 66b974b380d4
Revises: 
Create Date: 2026-08-13 22:31:33.112179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '66b974b380d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jd_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('section_type', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id')
    )
    op.create_index(op.f('ix_jd_chunks_analysis_id'), 'jd_chunks', ['analysis_id'], unique=False)
    op.create_table('resume_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('section_type', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id')
    )
    op.create_index(op.f('ix_resume_chunks_analysis_id'), 'resume_chunks', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_chunks_analysis_id'), table_name='resume_chunks')
    op.drop_table('resume_chunks')
    op.drop_index(op.f('ix_jd_chunks_analysis_id'), table_name='jd_chunks')
    op.drop_table('jd_chunks')
    # ### end Alembic commands ###
